[package]
name = "skyline_smash"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[lib]
name = "smash"

[dependencies]
libc = { git = "https://github.com/ultimate-research/libc-nnsdk" }
