[package]
name = "skyline_smash"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "A library for helping mod Smash Ultimate using skyline-rs"

[lib]
name = "smash"

[dependencies]
libc-nnsdk = "0.0.1"
compile-time-lua-bind-hash = "1.1"
